SRE-2522: New LICENSE file as expected by OpenSSF Scorecard
daos-stack/code_review pull request #35
Opened 2024-10-03 07:56 UTC by osalyk

Doc-only: true

2024-10-03 07:58 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2024-10-03 08:00 UTC, grom72 approved these changes

2024-10-03 09:43 UTC, grom72 approved these changes

2024-10-03 10:07 UTC, grom72 requested changes
Please add `Doc-only: true` pragma to commit message.

2024-10-04 07:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2024-10-04 07:42 UTC, janekmi approved these changes

2024-10-04 09:19 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2024-10-04 10:11 UTC, grom72 approved these changes

2024-10-07 17:50 UTC, merged